# -*- coding: utf-8 -*-
# Deployment settings for HeyBox2D.
# This file is autogenerated by the mkb system and used by the s3e deployment
# tool during the build process.

config = {}
cmdline = ['C:/Marmalade/7.4/s3e/makefile_builder/mkb.py', 'c:/Users/Ben/Desktop/FYP/FinalYearProject/box2d/heybox2d/HeyBox2D.mkb', '--deploy-only']
mkb = 'c:/Users/Ben/Desktop/FYP/FinalYearProject/box2d/heybox2d/HeyBox2D.mkb'
mkf = ['c:\\marmalade\\7.4\\s3e\\s3e-default.mkf', 'c:\\marmalade\\7.4\\modules\\iw2d\\iw2d.mkf', 'c:\\marmalade\\7.4\\modules\\legacy\\iw2d\\iw2d_legacy.mkf', 'c:\\marmalade\\7.4\\modules\\iwgx\\iwgx.mkf', 'c:\\marmalade\\7.4\\modules\\legacy\\iwgx\\iwgx_legacy.mkf', 'c:\\marmalade\\7.4\\modules\\iwgeom\\iwgeom.mkf', 'c:\\marmalade\\7.4\\modules\\iwutil\\iwutil.mkf', 'c:\\marmalade\\7.4\\modules\\third_party\\libjpeg\\libjpeg.mkf', 'c:\\marmalade\\7.4\\modules\\third_party\\libpng\\libpng.mkf', 'c:\\marmalade\\7.4\\modules\\third_party\\zlib\\zlib.mkf', 'c:\\marmalade\\7.4\\modules\\iwresmanager\\iwresmanager.mkf', 'c:\\marmalade\\7.4\\modules\\legacy\\iwresmanager\\iwresmanager_legacy.mkf', 'c:\\marmalade\\7.4\\modules\\iwgl\\iwgl.mkf', 'c:\\marmalade\\7.4\\modules\\iwgxfont\\iwgxfont.mkf', 'c:\\marmalade\\7.4\\modules\\legacy\\iwgxfont\\iwgxfont_legacy.mkf', 'c:\\marmalade\\7.4\\modules\\third_party\\tiniconv\\tiniconv.mkf', 'c:\\marmalade\\7.4\\examples\\examplescore\\examplescore.mkf', 'c:\\marmalade\\7.4\\examples\\marmaladeexampleresources\\marmaladeexampleresources.mkf', 'c:\\users\\ben\\desktop\\fyp\\finalyearproject\\box2d\\box2d.mkf']

class DeployConfig(object):
    pass

######### ASSET GROUPS #############

assets = {}

assets['Default'] = [
    ('c:/Users/Ben/Desktop/FYP/FinalYearProject/box2d/heybox2d/data/Image.png', 'Image.png', 0),
]

######### DEFAULT CONFIG #############

class DefaultConfig(DeployConfig):
    embed_icf = -1
    name = 'HeyBox2D'
    pub_sign_key = 0
    priv_sign_key = 0
    caption = 'HeyBox2D'
    long_caption = 'HeyBox2D'
    version = [0, 0, 1]
    config = ['c:/Users/Ben/Desktop/FYP/FinalYearProject/box2d/heybox2d/data/app.icf']
    data_dir = 'c:/Users/Ben/Desktop/FYP/FinalYearProject/box2d/heybox2d/data'
    mkb_dir = 'c:/Users/Ben/Desktop/FYP/FinalYearProject/box2d/heybox2d'
    iphone_link_lib = []
    osx_ext_dll = []
    wp81_extra_pri = []
    ws8_ext_capabilities = []
    android_external_res = []
    win32_ext_dll = []
    wp8_ext_capabilities = []
    ws81_ext_managed_dll = []
    iphone_link_libdir = []
    wp81_ext_capabilities = []
    android_extra_application_manifest = []
    ws8_ext_native_dll = []
    android_external_assets = []
    splashscreen = 'c:/marmalade/7.4/examples/marmaladeexampleresources/resources/splashscreens'
    blackberry_extra_descriptor = []
    ws8_extra_res = []
    android_extra_manifest = []
    wp81_ext_sdk_ref = []
    iphone_link_libdirs = []
    wp81_ext_device_capabilities = []
    icon = 'c:/marmalade/7.4/examples/marmaladeexampleresources/resources/icons'
    linux_ext_lib = []
    ws8_ext_managed_dll = []
    ws8_ext_sdk_manifest_part = []
    ws8_ext_device_capabilities = []
    ws81_extra_pri = []
    android_external_jars = []
    win8_winrt_extra_res = []
    wp81_ext_sdk_manifest_part = []
    android_supports_gl_texture = []
    wp81_extra_res = []
    wp81_ext_managed_dll = []
    ws81_ext_sdk_manifest_part = []
    ws81_ext_device_capabilities = []
    ws8_ext_sdk_ref = []
    iphone_extra_string = []
    tizen_so = []
    wp8_ext_native_dll = []
    win8_phone_extra_res = []
    win8_store_extra_res = []
    iphone_link_opts = []
    ws81_ext_sdk_ref = []
    wp8_extra_res = []
    ws81_ext_native_dll = []
    ws8_extra_pri = []
    wp8_ext_managed_dll = []
    android_so = []
    wp8_ext_sdk_ref = []
    osx_extra_res = []
    ws81_extra_res = []
    wp81_ext_native_dll = []
    ws81_ext_capabilities = []
    iphone_link_libs = []
    target = {
         'gcc_x86' : {
                   'debug'   : r'c:/Users/Ben/Desktop/FYP/FinalYearProject/box2d/heybox2d/build_heybox2d_vc11/Debug_HeyBox2D_VC11_gcc_x86/HeyBox2D.so',
                   'release' : r'c:/Users/Ben/Desktop/FYP/FinalYearProject/box2d/heybox2d/build_heybox2d_vc11/Release_HeyBox2D_VC11_gcc_x86/HeyBox2D.so',
                 },
         'gcc_x86_tizen' : {
                   'debug'   : r'c:/Users/Ben/Desktop/FYP/FinalYearProject/box2d/heybox2d/build_heybox2d_vc11/Debug_HeyBox2D_VC11_gcc_x86_tizen/HeyBox2D.s86',
                   'release' : r'c:/Users/Ben/Desktop/FYP/FinalYearProject/box2d/heybox2d/build_heybox2d_vc11/Release_HeyBox2D_VC11_gcc_x86_tizen/HeyBox2D.s86',
                 },
         'firefoxos' : {
                   'debug'   : r'c:/Users/Ben/Desktop/FYP/FinalYearProject/box2d/heybox2d/build_heybox2d_vc11/Debug_HeyBox2D_VC11_firefoxos/HeyBox2D.js',
                   'release' : r'c:/Users/Ben/Desktop/FYP/FinalYearProject/box2d/heybox2d/build_heybox2d_vc11/Release_HeyBox2D_VC11_firefoxos/HeyBox2D.js',
                 },
         'mips_gcc' : {
                   'debug'   : r'c:/Users/Ben/Desktop/FYP/FinalYearProject/box2d/heybox2d/build_heybox2d_vc11/Debug_HeyBox2D_VC11_gcc_mips/HeyBox2D.so',
                   'release' : r'c:/Users/Ben/Desktop/FYP/FinalYearProject/box2d/heybox2d/build_heybox2d_vc11/Release_HeyBox2D_VC11_gcc_mips/HeyBox2D.so',
                 },
         'arm_gcc' : {
                   'debug'   : r'c:/Users/Ben/Desktop/FYP/FinalYearProject/box2d/heybox2d/build_heybox2d_vc11/Debug_HeyBox2D_VC11_gcc_arm/HeyBox2D.s3e',
                   'release' : r'c:/Users/Ben/Desktop/FYP/FinalYearProject/box2d/heybox2d/build_heybox2d_vc11/Release_HeyBox2D_VC11_gcc_arm/HeyBox2D.s3e',
                 },
         'mips' : {
                   'debug'   : r'c:/Users/Ben/Desktop/FYP/FinalYearProject/box2d/heybox2d/build_heybox2d_vc11/Debug_HeyBox2D_VC11_gcc_mips/HeyBox2D.so',
                   'release' : r'c:/Users/Ben/Desktop/FYP/FinalYearProject/box2d/heybox2d/build_heybox2d_vc11/Release_HeyBox2D_VC11_gcc_mips/HeyBox2D.so',
                 },
         'gcc_x86_android' : {
                   'debug'   : r'c:/Users/Ben/Desktop/FYP/FinalYearProject/box2d/heybox2d/build_heybox2d_vc11/Debug_HeyBox2D_VC11_gcc_x86_android/HeyBox2D.so',
                   'release' : r'c:/Users/Ben/Desktop/FYP/FinalYearProject/box2d/heybox2d/build_heybox2d_vc11/Release_HeyBox2D_VC11_gcc_x86_android/HeyBox2D.so',
                 },
         'arm' : {
                   'debug'   : r'c:/Users/Ben/Desktop/FYP/FinalYearProject/box2d/heybox2d/build_heybox2d_vc11/Debug_HeyBox2D_VC11_arm/HeyBox2D.s3e',
                   'release' : r'c:/Users/Ben/Desktop/FYP/FinalYearProject/box2d/heybox2d/build_heybox2d_vc11/Release_HeyBox2D_VC11_arm/HeyBox2D.s3e',
                 },
         'x86' : {
                   'debug'   : r'c:/Users/Ben/Desktop/FYP/FinalYearProject/box2d/heybox2d/build_heybox2d_vc11/Debug_HeyBox2D_VC11_x86/HeyBox2D.s86',
                   'release' : r'c:/Users/Ben/Desktop/FYP/FinalYearProject/box2d/heybox2d/build_heybox2d_vc11/Release_HeyBox2D_VC11_x86/HeyBox2D.s86',
                 },
        }
    arm_arch = ''
    assets_original = assets
    assets = assets['Default']

default = DefaultConfig()
